apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-06-23T05:54:58Z'
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:alpine
        name: main
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 32Mi
